// public-frontend-svelte/src/lib/features/events/EventCard.svelte
<script lang="ts">
  import ButtonLink from '$lib/components/ui/ButtonLink.svelte';
  import type { EventItem } from './types';
  import { formatEventDateRange } from './utils';

  export let event: EventItem;
  export let featured = false;
</script>

<article class={`event-card ${featured ? 'event-card-featured' : ''}`}>
  <a href={`/events/${event.slug}`} class="event-card-image-link">
    <img src={event.posterImage || '/icons/lebedi.jpg'} alt={event.title} loading="lazy" decoding="async" />
    {#if featured}
      <div class="event-card-overlay-copy">
        <p class="event-date">{formatEventDateRange(event.startAt, event.endAt)}</p>
        <h3>{event.title}</h3>
      </div>
    {/if}
  </a>
  {#if !featured}
    <div class="event-card-content">
      <p class="event-date">{formatEventDateRange(event.startAt, event.endAt)}</p>
      <h3><a href={`/events/${event.slug}`}>{event.title}</a></h3>
      <p class="muted">{event.shortDescription}</p>
      <div class="event-actions">
        {#if event.ctaType === 'BOOKING' || event.ctaType === 'BOTH'}
          <ButtonLink href={`/booking?event=${event.slug}`} variant="primary">Забронювати</ButtonLink>
        {/if}
        {#if (event.ctaType === 'TICKETS' || event.ctaType === 'BOTH') && event.ticketUrl}
          <ButtonLink href={event.ticketUrl} variant="secondary" target="_blank">Квитки</ButtonLink>
        {/if}
      </div>
    </div>
  {/if}
</article>

// public-frontend/src/components/EventCard.jsx
import { Link } from 'react-router-dom';
import { formatEventDateRange } from '../lib/events';
import { localizeField } from '../lib/i18n';
import { useLocale } from '../state/locale';

export default function EventCard({ event, featured = false }) {
  const { locale } = useLocale();
  const title = localizeField(event.title, locale);
  const shortDescription = localizeField(event.shortDescription, locale);

  return (
    <article className={`event-card${featured ? ' featured' : ''}`}>
      <Link to={`/events/${event.slug}`} className="media-link">
        <img src={event.posterImage || '/icons/lebedi.jpg'} alt={title} loading="lazy" />
        <div className="event-overlay">
          <p className="event-date">{formatEventDateRange(event.startAt, event.endAt, locale === 'en' ? 'en-US' : 'ru-RU')}</p>
          <h3>{title}</h3>
          {shortDescription && <p className="muted" style={{ fontSize: '0.85rem', margin: '6px 0 12px' }}>{shortDescription}</p>}
          <div className="event-actions">
            <span className="btn btn-primary" style={{ fontSize: '0.8rem', padding: '8px 16px' }}>
              {locale === 'en' ? 'Details' : 'Подробнее'}
            </span>
          </div>
        </div>
      </Link>
    </article>
  );
}
